### ISSUE TITLE
Creating a Blog Post dumps you to a not-very-helpful page

### ISSUE THREAD

**Issue by davidcarvel** [therebelrobot/brigadehub#274]
#### Description

After writing a blog post, the page you go to is not very useful. I am not sure what the intended page/content to see is (e.g. I cannot create another blog post from this page, I cannot see my other posts).
#### Screenshots

![image](https://cloud.githubusercontent.com/assets/17933351/15167258/7115739e-16f5-11e6-8f3a-94314f3a51df.png)
#### Files

A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
#### To Reproduce

Go Home > Blog > New Post
Publish a new post.
#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Remember to use helpful labels and milestones. If you use the "help wanted" label, Code for America will [promote it widely](http://www.codeforamerica.org/geeks/civicissues).

**Comment by tracykm** [comment]
The page you are seeing is the blog post you just created. 

I think it is only confusing for these fake skeleton posts. But it would also make since to go to the index blog page, or new form, with a link in the flash message to the full post page you created. Wither way we should probably make it consistent with projects and events.
